import type { Metadata } from "next";
import "./globals.css";
import { cn } from '@/lib/utils'

import { Toaster } from "@/components/ui/toaster"
import { Nunito } from 'next/font/google'
import { Open_Sans } from 'next/font/google'

const fontHeading = Nunito({
  weight: ['400','700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Open_Sans({
  weight: ['400','700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}
      >
      {children}
      <Toaster />
      </body>
    </html>
  );
}